application: mjs-share-card
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /js_logo\.png
  static_files: js_logo.png
  upload: js_logo\.png

- url: /image
  script: image.php

- url: /.*
  script: main.php
